version: "2"
services:
  node:
    image: "node:16"
    user: "node"
    working_dir: /home/jackson/jacksonwearn
    environment:
      - NODE_ENV=production
    volumes:
      - /home/jackson/jacksonwearn:/home/node/app
    expose:
      - "8081"
    command: "npm start"
